apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: webserver-operator.v1.0.34
  namespace: placeholder
  annotations:
    categories: Application Runtime
    capabilities: Basic Install
    description: An Ansible-based operator that deploys NGINX or Apache based on a WebServer CR.

    # OLM bundle metadata #
    operators.operatorframework.io.bundle.package.v1: webserver-operator-dev
    operators.operatorframework.io.bundle.channels.v1: stable
    operators.operatorframework.io.bundle.channel.default.v1: stable

    # Operator image (pinned)
    containerImage: quay.io/philip860/webserver-operator:v1.0.34-dev

    # Console sample CR
    alm-examples: >-
      [
        {
          "apiVersion": "example.com/v1alpha1",
          "kind": "WebServer",
          "metadata": { "name": "example-webserver" },
          "spec": {
            "type": "nginx",
            "replicas": 1,
            "port": 8080
          }
        }
      ]

    # Required feature flags (must be strings "true"/"false")
    features.operators.openshift.io/disconnected: "false"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"

    # Bundle layout
    operators.operatorframework.io.bundle.mediatype.v1: registry+v1
    operators.operatorframework.io.bundle.manifests.v1: manifests/
    operators.operatorframework.io.bundle.metadata.v1: metadata/

    # Allow clusters on older 1.0.x releases to upgrade directly to 1.0.34
    # even if intermediate versions are missing from some catalog/index builds.
    olm.skipRange: ">=1.0.0 <1.0.34"

spec:
  displayName: WebServer Operator
  description: |-
    The WebServer Operator manages WebServer custom resources which can
    deploy either NGINX or Apache HTTPD behind a Service and OpenShift Route.
  maturity: stable
  version: 1.0.34

  # Replace the last known-good public stable version in the catalog
  replaces: webserver-operator.v1.0.33

  provider:
    name: Duncan-Networks

  #### Icon Place Holder Section ###############
  # icon:
 
      # mediatype: image/svg+xml
  keywords:
    - nginx
    - apache
    - webserver
    - ansible
  relatedImages:
    - name: webserver-operator
      image: quay.io/philip860/webserver-operator:v1.0.34-dev
  install:
    strategy: deployment
    spec:
      deployments:
        - name: webserver-operator
          spec:
            selector:
              matchLabels:
                name: webserver-operator
            replicas: 1
            template:
              metadata:
                labels:
                  name: webserver-operator
              spec:
                serviceAccountName: webserver-operator
                containers:
                  - name: ansible-operator
                    image: quay.io/philip860/webserver-operator:v1.0.34-dev
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: webserver-operator
                      - name: WEBSERVER_OPERATOR_VERSION
                        value: "v1.0.34-dev"
      permissions:
        - serviceAccountName: webserver-operator
          rules:
            - apiGroups:
                - example.com
              resources:
                - webservers
                - webservers/status
                - webservers/finalizers
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - apps
              resources:
                - deployments
                - replicasets
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ''
              resources:
                - pods
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - ''
              resources:
                - services
                - configmaps
                - secrets
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ''
              resources:
                - events
              verbs:
                - create
                - patch
                - update
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
      clusterPermissions:
        - serviceAccountName: webserver-operator
          rules:
            - apiGroups:
                - ''
              resources:
                - namespaces
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
              verbs:
                - get
                - list
                - watch
  customresourcedefinitions:
    owned:
      - name: webservers.example.com
        version: v1alpha1
        kind: WebServer
        displayName: WebServer
        description: Custom resource that declares an Apache or NGINX deployment.
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: true
