---
collections:
  - name: kubernetes.core.k8s
    # Optional: pin a version if you want
    # version: ">=2.4.0"

  - name: operator_sdk.util
    # Optional: you can pin a version here as well
    # version: ">=0.0.0"
